Feat: hb number generation
flaxandteal/coral-arches pull request #349
Opened 2024-07-18 12:52 UTC by taylorn01

2024-07-30 10:03 UTC, StuCM requested changes
Designation workflow works with transferring the data to and from the revision.
Number generation works but as pointed out in the comments, some bugs present in the validation

2024-07-30 16:06 UTC, StuCM commented
I've updated the changes for this, would someone be able to test the changes:

### Test
- Hit generate HB number multiple times before saving - This should save successfully without any alerts
- Create 2 Buildings at the same time so that they generate with the same number. Save one and then save the second. In the search you should see one has saved with the incremented number
- Use the save and continue at the end and then save and complete. The HB number should still be in the resource and shown as the model name

2024-08-02 13:42 UTC, taylorn01 commented
lgtm all works as described, found out that the ha number function isn't even attached to the model and also dosen't work without a 500. opening a ticket to fix it

2024-08-02 13:43 UTC, taylorn01 reviewed
lgtm

2024-08-02 13:43 UTC, merged