Feature/assign consultation workflow
flaxandteal/coral-arches pull request #37
Opened 2023-10-13 13:54 UTC by OwenGalvia

Includes changes to consultation model

2023-10-13 14:42 UTC, taylorn01 commented
Needs version 0.4.2

2023-10-16 14:50 UTC, OwenGalvia commented
> Needs version 0.4.2

done

2023-10-17 15:09 UTC, taylorn01 approved these changes
Looks good just want to double check that they don't already have important data created using the consultation model because it could make it difficult to update

2023-10-20 11:43 UTC, OwenGalvia commented
@taylorn01 
0.6.4 has a clone of the model and uses that for this workflow. It works apart from the documentation step which frustratingly posts the tile correctly but gives a 500 claiming there is a key error 'nodegroup_id'. The documentation is added to the resource instance as expected, seems to be an issue with the actual workflow step.
I'm taking a break from this and moving to something else. I'll come back to it early next week unless you happen to know what the issue is.

2023-10-27 08:32 UTC, taylorn01 requested changes

2023-10-27 08:32 UTC, taylorn01 commented on coral/coral/pkg/graphs/resource_models/Consultation.json
>                      "helpenabled": false,
Take a copy of this so we can use it in the future to replace the current consultation model on develop and then reset this back to how it is on develop

2023-10-27 08:32 UTC, taylorn01 commented on coral/coral/settings.py
> +APP_VERSION = '0.6.4'
Make this match the version on develop and the auto updating will take effect

2023-10-30 16:26 UTC, merged